version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: electroshop-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: electroshop
      POSTGRES_PASSWORD: electroshop_dev_password
      POSTGRES_DB: electroshop
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U electroshop"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - electroshop-network

  backend:
    build: .
    container_name: electroshop-backend
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://electroshop:electroshop_dev_password@postgres:5432/electroshop
      PORT: 3000
      NODE_ENV: development
      JWT_ACCESS_SECRET: 19152891b0ad37f6ba4a41ec8151dbc9ca6852642ee67a0ef4e8f92729bc997c
      JWT_REFRESH_SECRET: 3338d2d513b197b7d3ed42754ca9c9981a8716fdc3ba2dff659c2af8d938252e
      JWT_ACCESS_EXPIRES_IN: 15m
      JWT_REFRESH_EXPIRES_IN: 7d
      ALLOWED_ORIGINS: http://localhost:8081,exp://192.168.1.100:8081
      CLOUDINARY_CLOUD_NAME: djo2iaa9m
      CLOUDINARY_UPLOAD_PRESET: electroshop_products
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - electroshop-network

networks:
  electroshop-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
